name: Publish Docker image to Docker Hub
on: 
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build ./api/ -t echelonkay/devops-qr-code-api:latest
      - name: push image to docker hub
        run: |
            docker push echelonkay/devops-qr-code-api:latest
