name: Build and Publish Image to Docker Hub

on:
  [workflow_dispatch]  # This allows manual triggering from GitHub UI

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "echelonkay" --password-stdin
        
      - name: Build API image
        run: docker build ./api/ -t echelonkay/devops-qr-code-api:latest --no-cache
        
      - name: Build Frontend image
        run: docker build ./front-end-nextjs/ -t echelonkay/devops-qr-code-frontend:latest --no-cache
        
      - name: Push API image to Docker Hub
        run: docker push echelonkay/devops-qr-code-api:latest
        
      - name: Push Frontend image to Docker Hub
        run: docker push echelonkay/devops-qr-code-frontend:latest
