name: Build and Publish Docker Images

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "echelonkay" --password-stdin

      # Step 3: Build API Docker image
      - name: Build API Docker image
        run: docker build ./api/ -t echelonkay/devops-qr-code-api:latest --no-cache

      # Step 4: Build Frontend Docker image
      - name: Build Frontend Docker image
        run: docker build ./front-end-nextjs/ -t echelonkay/devops-qr-code-frontend:latest --no-cache

      # Step 5: Push API Docker image to Docker Hub
      - name: Push API Docker image
        run: docker push echelonkay/devops-qr-code-api:latest

      # Step 6: Push Frontend Docker image to Docker Hub
      - name: Push Frontend Docker image
        run: docker push echelonkay/devops-qr-code-frontend:latest
